### ISSUE TITLE
License

### ISSUE THREAD

**Issue by LucasAppel** [VisualBean/vue-splash#14]
Hi,

I could not find any information about the license. Am I allowed to use (parts of) the code in my project for university? I mean it's simple code but it's still your code!
Thank you in advance.

Lucas

**Comment by VisualBean** [comment]
Ofcourse you can! I will get a license added. No need to attribute me
either 🙂

/Alex

**Comment by VisualBean** [comment]
Ive added a License 🙂 - the unlicense. so you are free to do what you want with the code. Thanks for reaching out though! 
Have a great day @LucasAppel

**Comment by LucasAppel** [comment]
Wow, thanks for the fast reply and the (un)license!
Have a nice day! :)
